name: T6

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@master

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}

      # from: https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: run
        run: |
          export TZ='Asia/Shanghai'
          npm run cron_t6
        env:
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          T6_BASE_URL: ${{ secrets.T6_BASE_URL }}
